version: '3.2'

networks:
  postgres-network:
    driver: bridge

services:
  POSTGRES:
    container_name: pg
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    volumes:
      - ~/.docker/postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: unless-stopped